export const Constants = {

    FETCH_CANDIDATE_BEGIN:"FETCH_CANDIDATE_BEGIN",
    FETCH_CANDIDATE_SUCCESS:"FETCH_CANDIDATE_SUCCESS",
    FETCH_CANDIDATE_FAILURE:"FETCH_CANDIDATE_FAILURE",
    FETCH_QUESTIONS_BEGIN:"FETCH_QUESTIONS_BEGIN",
    FETCH_QUESTIONS_SUCCESS:"FETCH_QUESTIONS_SUCCESS",
    FETCH_QUESTIONS_FAILURE:"FETCH_QUESTIONS_FAILURE",
    FETCH_APPLICATIONS_BEGIN:"FETCH_APPLICATIONS_BEGIN",
    FETCH_APPLICATIONS_SUCCESS:"FETCH_APPLICATIONS_SUCCESS",
    FETCH_APPLICATIONS_FAILURE:"FETCH_APPLICATIONS_FAILURE",

}